services:
  bechirach-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: bechirah-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - WEBHOOK_BASE_URL=${WEBHOOK_BASE_URL:-http://localhost:5678/webhook}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - nginx_net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  nginx_net:
    external: true
